config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: %i[index show new create edit update destroy] do
    resources :relationships, only: %i[create destroy]
    resources :followees, only: %i[index], module: :users
    resources :followers, only: %i[index], module: :users
  end

  resources :posts, only: %i[index show new create edit update destroy] do
    resources :favorites, only: %i[create destroy]
    scope module: :posts do
      resources :comments, only: %i[create]
    end
  end

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 140 }
end

app/models/comment/build_form.rb
# frozen_string_literal: true

class Comment
  class BuildForm
    # NOTE: これをincludeすると、errorsやvalidates、valid?とかが使えるようになる。
    include ActiveModel::Validations

    # Ref: https://railsguides.jp/active_record_validations.html#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89
    validate :comment_valid?

    # @param params [Hash]
    # @param user_id [Integer]
    # @param user_id [Post]
    def initialize(params:, user_id:, post:)
      @params = params
      @user_id = user_id
      @post = post
    end

    def save
      comment
      return false unless comment.valid?

      ActiveRecord::Base.transaction do
        raise ActiveRecord::Rollback unless save_record!(comment)
      end

      true
    end

    # @return [Comment]
    def comment
      @comment || Comment.new(
        comment: params[:comment],
        post:,
        user_id:
      )
    end

    attr_reader :params, :post, :user_id

    private

    def save_record!(record)
      return true if record.save

      record.errors.full_messages.each do |message|
        errors.add(:base, message)
      end
      raise ActiveRecord::Rollback
    end

    def comment_valid?
      return if comment.valid?

      comment.errors.each do |error|
        errors.add(:base, error.full_message)
      end
    end
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :check_logged_in, only: %i[show create]

  # GET /posts/:post_id/comments/:id
  def show
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @ancestors = @comment.ancestors.order(id: :asc).preload(:user)
    @descendants = @comment.descendants.without_self.where(parent_id: @comment.id).preload(:user)
    @parent_id = @comment.id
    fetch_descendant_counts(@ancestors + @descendants)
  end

  # POST /posts/:post_id/comments
  def create
    form = Comment::BuildForm.new(
      user_id: session[:user_id],
      post: current_post,
      params: create_params
    )
    if form.save
      flash[:success] = 'コメントが作成されました'
      redirect_to post_comment_url(form.post, form.comment)
    else
      flash[:alert] = "コメントの作成に失敗しました #{form.errors.full_messages.to_sentence}"
      render partial: 'comments/form', locals: { post: form.post, comment: form.comment }, status: :unprocessable_entity
    end
  end

  private

  def current_post
    @current_post ||= Post.find(params[:post_id])
  end

  def create_params
    # params.require(:comment).permit(:comment, :parent_id).merge(user_id: current_user.id)
    params.require(:comment).permit(:comment, :parent_id)
  end

  def fetch_descendant_counts(comments)
    descendant_counts = TreePath.where(ancestor_id: comments.pluck(:id)).group(:ancestor_id).count(:descendant_id)
    @descendant_counts = {}
    descendant_counts.each do |ancestor_id, count|
      @descendant_counts[ancestor_id] = count
    end
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    before_action :check_logged_in, only: %i[create]

    # POST /posts/:post_id/comments
    def create
      form = resolve_create_form
      if form.save
        flash[:success] = 'コメントが作成されました'
        redirect_to post_url(form.post)
      else
        flash[:alert] = "コメントの作成に失敗しました #{form.errors.full_messages.to_sentence}"
        render partial: 'posts/comments/form', locals: { post: form.post }, status: :unprocessable_entity
      end
    end

    private

    def create_params
      params.require(:comment).permit(:comment)
    end

    def resolve_create_form
      Comment::BuildForm.new(
        user_id: session[:user_id],
        post: Post.find(params[:post_id]),
        params: create_params
      )
    end
  end
end

app/views/comments/_comment.html.erb
<div class="comments">
  <% if comments.empty? %>
    <p>コメントはまだありません</p>
  <% else %>
    <% comments.each do |comment| %>
      <article class="media">
        <div class="media-content">
          <div class="comment-wrapper">
            <p><%= link_to comment.user.email, user_path(comment.user) %></p>
            <p>
              <%= simple_format(comment.comment) %>
            </p>

            <p>
              <span>
                <%= link_to post_comment_path(@post, comment) do %>
                  <span class="material-icons", style="color: #4A9A98;">
                    mode_comment
                  </span>
                <% end %>
                <%= @descendant_counts[comment.id] - 1 %>
              </span>
              <span>
                <span class="material-icons">
                  upload
                </span>
                <small>
                  <%= comment.created_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M:%S") %>
                </small>
              <span>
              <span>
                <span class="material-icons">
                  update
                </span>
                <small>
                  <%= comment.updated_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M:%S") %>
                </small>
              </span>
            </p>
          </div>
        </div>
      </article>
    <% end %>
  <% end %>
</div>

app/views/comments/_comment_form.html.erb
<style>
  div.comment-form-wrapper {
    width: 100%;
    margin: 2rem auto;
  }

  form {
    width: 100%;
  }

  .textarea {
    width: 100%;
    margin: 0;
    resize: none;
  }
</style>

<div class="comment-form-wrapper">
  <div class="field is-grouped">
    <%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
      <%= render 'shared/error_messages', { object: form.object } %>

      <div class="field">
        <label class="label"><%= form.label 'コメントする' %></label>
        <%= form.text_area :comment, class: 'content-box textarea is-rounded', placeholder: 'コメント', size: '30x10', maxlength: '140' %>
      </div>

      <div class="field">
        <%= form.submit 'コメントする', class: 'button is-primary has-text-white is-rounded is-fullwidth' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<style>
  div.comment-form-wrapper {
    width: 100%;
    margin: 2rem auto;
  }

  form {
    width: 100%;
  }

  .textarea {
    width: 100%;
    margin: 0;
    resize: none;
  }
</style>

<div class="comment-form-wrapper">
  <div class="field is-grouped">
    <%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
      <%= render 'shared/error_messages', { object: form.object } %>

      <div class="field">
        <label class="label"><%= form.label 'コメントする' %></label>
        <%= form.text_area :comment, class: 'content-box textarea is-rounded', placeholder: 'コメント', size: '30x10', maxlength: '140' %>
      </div>

      <%= form.hidden_field :parent_id, value: @parent_id %>

      <div class="field">
        <%= form.submit 'コメントする', class: 'button is-primary has-text-white is-rounded is-fullwidth' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_reply_form.html.erb
<style>
  div.comment-form-wrapper {
    width: 100%;
    margin: 2rem auto;
  }

  form {
    width: 100%;
  }

  .textarea {
    width: 100%;
    margin: 0;
    resize: none;
  }
</style>

<div class="comment-form-wrapper">
  <div class="field is-grouped">
    <%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
      <%= render 'shared/error_messages', { object: form.object } %>

      <div class="field">
        <label class="label"><%= form.label 'コメントする' %></label>
        <%= form.text_area :comment, class: 'content-box textarea is-rounded', placeholder: 'コメント', size: '30x10', maxlength: '140' %>
      </div>

      <%= form.hidden_field :is_reply, value: @is_reply %>

      <div class="field">
        <%= form.submit 'コメントする', class: 'button is-primary has-text-white is-rounded is-fullwidth' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/show.html.erb
<% provide(:title, 'コメント詳細' + @post.title) %>

<style>
  .field.has-addons {
    width: 100%;
  }

  div.control {
    width: 50%;
  }

  div.descendant-comments {
    margin-left: 10%;
  }
</style>

<div class="contents-wrapper">
  <h1>ポスト</h1>
  <%= render 'layouts/flash' %>

  <article class="media">
    <div class="media-content">
      <p>
        <strong><%= link_to @post.user.email, user_path(@post.user) %></strong>
      </p>
      <p><%= link_to @post.title, post_path(@post) %></p>
      <p><%= simple_format(@post.content) %></p>
      <p>
        <small>投稿日時：<%= @post.created_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M:%S") %></small>
        <br>
        <small>更新日時：<%= @post.updated_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M:%S") %></small>
      </p>
    </div>
  </article>

  <div>
    <%= link_to 'ポスト一覧', posts_path, class: 'button is-primary is-outlined is-rounded is-fullwidth' %>
  </div>

  <h3>ここまでのコメント</h3>
  <div class="ancestor-comments">
    <%= render 'comments/comment', { comments: @ancestors } %>
  </div>

  <div class="reply-form">
    <%= render 'comments/reply_form' %>
  </div>

  <h3>みんなのコメント</h3>
  <div class="descendant-comments">
    <%= render 'comments/comment', { comments: @descendants } %>
  </div>
</div>