config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: %i[index show new create edit update destroy] do
    resources :relationships, only: %i[create destroy]
    resources :followees, only: %i[index], module: :users
    resources :followers, only: %i[index], module: :users
  end

  resources :posts, only: %i[index show new create edit update destroy] do
    resources :favorites, only: %i[create destroy]
    scope module: :posts do
      resources :comments, only: %i[create]
    end
  end

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  module UserFavoriteExtension
    def indexed_favorites_by_post_id
      @indexed_favorites_by_post_id ||= index_by(&:post_id)
    end
  end

  module UserRelationshipExtension
    def indexed_followees_by_followee_id
      @indexed_followees_by_followee_id ||= index_by(&:followee_id)
    end

    def indexed_followers_by_follower_id
      @indexed_followers_by_follower_id ||= index_by(&:follower_id)
    end
  end

  has_many :posts, dependent: :destroy, inverse_of: :user
  has_many :comments, dependent: :destroy, inverse_of: :user
  has_many :favorites, -> { extending UserFavoriteExtension }, dependent: :destroy, inverse_of: :user
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :active_relationships, -> { extending UserRelationshipExtension },
           class_name: 'ActiveRelationship',
           foreign_key: 'follower_id',
           dependent: :destroy,
           inverse_of: :follower
  has_many :passive_relationships, -> { extending UserRelationshipExtension },
           class_name: 'PassiveRelationship',
           foreign_key: 'followee_id',
           dependent: :destroy,
           inverse_of: :followee
  has_many :followees, through: :active_relationships, source: :followee
  has_many :followers, through: :passive_relationships, source: :follower

  has_secure_password

  validates :email, presence: true

  def favorited?(post_id)
    favorites.indexed_favorites_by_post_id[post_id].present?
  end

  def follow(followee)
    ActiveRelationship.follow(self, followee)
  end

  def unfollow(followee)
    ActiveRelationship.unfollow(self, followee)
  end

  def followee?(followee)
    active_relationships.indexed_followees_by_followee_id[followee.id].present?
  end
end

app/controllers/users/followees_controller.rb
# frozen_string_literal: true

module Users
  class FolloweesController < ApplicationController
    before_action :check_logged_in

    # GET /users/:user_id/followees
    def index
      @user = User.find(params[:user_id])
      @followees = @user.followees
      @followees_counts = ActiveRelationship.where(follower_id: @followees.pluck(:id)).group(:follower_id).count
      @followers_counts = PassiveRelationship.where(followee_id: @followees.pluck(:id)).group(:followee_id).count
      @followees_by_user = current_user.active_relationships.index_by(&:followee_id)
    end
  end
end

app/controllers/users/followers_controller.rb
# frozen_string_literal: true

module Users
  class FollowersController < ApplicationController
    before_action :check_logged_in

    # GET /users/:user_id/followers
    def index
      @user = User.find(params[:user_id])
      @followers = @user.followers
      @followees_counts = ActiveRelationship.where(follower_id: @followers.pluck(:id)).group(:follower_id).count
      @followers_counts = PassiveRelationship.where(followee_id: @followers.pluck(:id)).group(:followee_id).count
      @followees_by_user = current_user.active_relationships.index_by(&:followee_id)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :check_logged_in, only: %i[index show]
  before_action :authorize_user_edit, only: %i[edit update destroy]

  # GET /users
  def index
    @users = User.all
    @followees_counts = Relationship.where(follower_id: @users.pluck(:id)).group(:follower_id).count
    @followers_counts = Relationship.where(followee_id: @users.pluck(:id)).group(:followee_id).count
    @followees_by_user = current_user.active_relationships.index_by(&:followee_id)
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  # GET /users/new
  def new
    @user = User.new
    render layout: 'login_layout'
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user, notice: 'アカウントの作成に成功しました'
    else
      flash.now[:alert] = 'アカウントの作成に失敗しました'
      render :new, layout: 'login_layout', status: :unprocessable_entity
    end
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/:id
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: 'アカウント情報を更新しました'
    else
      flash.now[:alert] = 'アカウント情報の更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /users/:id
  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to users_url, notice: 'ユーザーは削除されました', status: :see_other
    else
      redirect_to users_url, alert: 'ユーザーの削除に失敗しました'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def authorize_user_edit
    check_edit_authority(user_id: params[:id], redirect_url: users_url)
  end
end

app/views/users/_form.html.erb
<style>
  div.user-form-wrapper {
    margin: 0 auto;
  }

  form {
    width: 100%;
  }

  .field-body {
    display: block;
    margin-right: 20%;
  }
</style>

<div class="user-form-wrapper">
  <%= form_with(model: @user, local: true) do |form| %>
    <div class="has-text-danger">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <%= form.label :email, class: 'label' %>
      </div>
      <div class="field-body">
        <div class="control">
          <div class="field">
            <p class="control">
              <%= form.email_field :email, autofocus: true, class: 'input is-rounded', placeholder: 'email@example.com' %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label is-normal">
        <%= form.label :password, class: 'label' %>
      </div>
      <div class="field-body">
        <div class="control">
          <div class="field">
            <p class="control">
              <%= form.password_field :password, class: 'input is-rounded' %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label"></div>
      <div class="field-body">
        <div class="control">
          <%= form.submit '送信', class: 'button is-primary has-text-white is-rounded is-fullwidth' %>
        </div>
      </div>
    </div>

    <div class="field is-horizontal">
      <div class="field-label"></div>
      <div class="field-body">
        <div class="control">
          <%= link_to 'キャンセル', back_path, class: 'button is-primary is-rounded is-outlined is-fullwidth' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_list.html.erb
<style>
  table {
    width: 100%;
  }
</style>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>E-mail</th>
      <th>フォロー</th>
      <th>フォロワー</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <th><%= user.id %></th>
        <td><%= link_to user.email, user_path(user) %></td>
        <td><%= link_to (@followees_counts[user.id] || 0), user_followees_path(user.id) %></td>
        <td><%= link_to (@followers_counts[user.id] || 0), user_followers_path(user.id) %></td>

        <% if session[:user_id] == user.id %>
          <td>
            <%= link_to '削除', user_path(user), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'button is-danger has-text-white is-rounded is-fullwidth' %>
          </td>
        <% else %>
          <td>
            <% if current_user != user %>
              <% if current_user.followee?(user) %>
                <% relationship = @followees_by_user[user.id] %>
                <%= link_to 'フォロー中', user_relationship_path(user.id, relationship), data: { turbo_method: :delete }, class: (defined?(options) && options[:class].presence) || 'button is-primary is-rounded has-text-white is-fullwidth' %>
              <% else %>
                <%= link_to 'フォローする', user_relationships_path(user.id), data: { turbo_method: :post }, class: (defined?(options) && options[:class].presence) || 'button is-primary is-rounded is-outlined is-fullwidth' %>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/edit.html.erb
<% provide(:title, 'User情報編集') %>

<div class="contents-wrapper">
  <h1>ユーザー情報編集</h1>

  <%= render 'layouts/flash' %>
  <%= render 'form', { back_path: user_path(@user) } %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'User一覧') %>



<div class="contents-wrapper">
  <h1>Users リスト</h1>

  <%= render 'layouts/flash' %>

  <%= render 'users/list', { users: @users, followees: @followees_by_user} %>
</div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>

<div class="contents-wrapper">
  <h1>新規登録</h1>

  <%= render 'layouts/flash' %>
  <%= render 'form', { back_path: login_path } %>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User詳細') %>

<style>
  form {
    width: 100%;
  }

  .field-body {
    display: block;
    margin-right: 20%;
  }
</style>

<div class="contents-wrapper">
  <h1>User 詳細</h1>

  <%= render 'layouts/flash' %>

  <div>
    <%= form_with(model: @user, local: true) do |form| %>
      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <%= form.label :id, class: 'label' %>
        </div>
        <div class="field-body">
          <div class="control">
            <div class="field">
              <p class="control">
                <%= form.text_field :id, class: 'input is-rounded', readonly: true %>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label is-normal">
          <%= form.label :email, class: 'label' %>
        </div>
        <div class="field-body">
          <div class="control">
            <div class="field">
              <p class="control">
                <%= form.email_field :email, class: 'input is-rounded', readonly: true %>
              </p>
            </div>
          </div>
        </div>
      </div>

      <% if session[:user_id] == @user.id %>
        <div class="field is-horizontal">
          <div class="field-label"></div>
          <div class="field-body">
            <div class="control">
              <%= link_to 'ユーザー情報編集', edit_user_path(@user), class: 'button is-primary has-text-white is-rounded is-fullwidth' %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="field is-horizontal">
          <div class="field-label"></div>
          <div class="field-body">
            <div class="control">
              <%= render 'relationships/btn', user: @user %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="field is-horizontal">
        <div class="field-label"></div>
        <div class="field-body">
          <div class="control">
            <%= link_to 'ユーザー一覧', users_path, class: 'button is-primary is-rounded is-outlined is-fullwidth' %>
          </div>
        </div>
      </div>

      <div class="field is-horizontal">
        <div class="field-label"></div>
        <div class="field-body">
          <div class="control">
            <table>
              <tr>
                <td><%= link_to "#{@user.followees.count}フォロー", user_followees_path(@user) %></td>
                <td><%= link_to "#{@user.followers.count}フォロワー", user_followers_path(@user) %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>