config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: %i[index show new create edit update destroy] do
    resources :relationships, only: %i[create destroy]
    resources :followees, only: %i[index], module: :users
    resources :followers, only: %i[index], module: :users
  end

  resources :posts, only: %i[index show new create edit update destroy] do
    resources :favorites, only: %i[create destroy]
    scope module: :posts do
      resources :comments, only: %i[create]
    end
  end

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="notification is-danger is-light">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<style>
  div.header-wrapper {
    width: 100%;
  }

  header.hero {
    background-color: #D4ECEA;
    color: #4A9A98;
  }

  h1.title {
    color: #4A9A98;
    text-arigen: center;
  }
</style>

<div class="header-wrapper">
  <header class="hero is-small">
    <div class="hero-body">
      <h1 class="title has-text-centered">さみだれ</h1>

      <% if current_user.present? %>
        <p class="current-user"><%= current_user.email %>でログイン中です</p>
      <% end %>
    </div>
  </header>
</div>

app/views/shared/_tab_menu.html.erb
<style>
  div.menu-wrapper {
    position: sticky;
    top: 0;
    background-color: #FFF;
    z-index: 1;
  }

  @media screen and (max-width: 767px) {
    aside.menu {
      display: none;
    }
  }

  @media screen and (min-width: 767px) {
    div.menu-wrapper {
      flex-basis: 25%;
    }

    div.tabs {
      display: none;
    }

    aside.menu {
      position: sticky;
      top: 0;
    }

    ul.menu-list {
      list-style: none;
    }
  }

</style>

<div class="menu-wrapper">
  <div class="tabs">
    <ul>
      <li><%= link_to 'Home', posts_path %></li>
      <li><%= link_to '新規投稿', new_post_path %></li>
      <li><%= link_to 'User', user_path(current_user) %></li>
      <li>
        <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete, turbo_confirm: '本当にログアウトしますか？' } %>
      </li>
    </ul>
  </div>

  <aside class="menu">
    <ul class="menu-list">
      <li><%= link_to 'Home', posts_path %></li>
      <li><%= link_to '新規投稿', new_post_path %></li>
      <li><%= link_to 'User', user_path(current_user) %></li>
      <li>
        <%= link_to 'ログアウト', logout_path, data: { turbo_method: :delete, turbo_confirm: '本当にログアウトしますか？' } %>
      </li>
    </ul>
  </aside>
</div>