config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'favorites/create'
  get 'favorites/destroy'
  get 'sessions/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users, only: %i[index show new create edit update destroy] do
    resources :relationships, only: %i[create destroy]
    resources :followees, only: %i[index], module: :users
    resources :followers, only: %i[index], module: :users
  end

  resources :posts, only: %i[index show new create edit update destroy] do
    resources :favorites, only: %i[create destroy]
    scope module: :posts do
      resources :comments, only: %i[create]
    end
  end

  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  POSTS_PER_PAGE = 20

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_by_users, through: :favorites, source: :user
  has_many :comments, dependent: :destroy

  validates :user_id, presence: true
  validates :title,   presence: true, length: { maximum: 30 }
  validates :content, presence: true, length: { maximum: 140 }

  before_validation :set_default_values

  class << self
    def resolve_posts_with_pagination(query: nil, last_post_id: nil, first_post_id: nil)
      if query
        resolve_posts_searched_with_query_and_cursors(query:, last_post_id:,
                                                      first_post_id:)
      else
        resolve_posts_and_cursors(last_post_id:, first_post_id:)
      end
    end

    private

    def resolve_cursors(posts:)
      next_cursor = posts.last&.id
      prev_cursor = posts.first&.id

      [next_cursor, prev_cursor]
    end

    def resolve_posts_and_cursors(last_post_id: nil, first_post_id: nil)
      posts = resolve_posts_with_no_query(last_post_id:, first_post_id:)
      posts = order(id: :desc).limit(POSTS_PER_PAGE).eager_load(:user) if posts.empty?

      next_cursor, prev_cursor = resolve_cursors(posts:)

      [posts, next_cursor, prev_cursor]
    end

    def resolve_posts_searched_with_query(sanitized_query:, last_post_id: nil, first_post_id: nil)
      if last_post_id
        Post.find_by_sql(resolve_query_with_cursor(sanitized_query:, cursor: last_post_id,
                                                   direction: :desc))
      elsif first_post_id
        posts = Post.find_by_sql(resolve_query_with_cursor(sanitized_query:, cursor: first_post_id,
                                                           direction: :asc))
        posts.reverse
      else
        Post.find_by_sql(resolve_query(sanitized_query:))
      end
    end

    def resolve_posts_searched_with_query_and_cursors(query: nil, last_post_id: nil, first_post_id: nil)
      sanitized_query = sanitize_sql_like(query)
      posts = resolve_posts_searched_with_query(sanitized_query:, last_post_id:, first_post_id:)

      posts = Post.find_by_sql(resolve_query(sanitized_query:)) if posts.empty?

      resolve_preloading_user(posts:)

      next_cursor, prev_cursor = resolve_cursors(posts:)

      [posts, next_cursor, prev_cursor]
    end

    def resolve_posts_with_no_query(last_post_id: nil, first_post_id: nil)
      if last_post_id
        where('posts.id < ?', last_post_id).order(id: :desc).limit(POSTS_PER_PAGE).eager_load(:user)
      elsif first_post_id
        posts = where('posts.id > ?', first_post_id).order(id: :asc).limit(POSTS_PER_PAGE).eager_load(:user)
        posts.reverse
      else
        order(id: :desc).limit(POSTS_PER_PAGE).eager_load(:user)
      end
    end

    def resolve_preloading_user(posts:)
      ActiveRecord::Associations::Preloader.new(records: posts, associations: :user).call
    end

    def resolve_query(sanitized_query:)
      Post.sanitize_sql_array([
                                <<~SQL,
                                  (SELECT * FROM posts WHERE content LIKE ?)
                                  UNION ALL
                                  (SELECT * FROM posts WHERE title LIKE ?)
                                  ORDER BY id DESC
                                  LIMIT #{POSTS_PER_PAGE}
                                SQL
                                "#{sanitized_query}%", "#{sanitized_query}%"
                              ])
    end

    def resolve_query_with_cursor(sanitized_query:, cursor:, direction:)
      order = direction == :asc ? 'ASC' : 'DESC'
      comparator = direction == :asc ? '>' : '<'

      resolve_query_with_order_and_comparator(sanitized_query:, cursor:, order:, comparator:)
    end

    def resolve_query_with_order_and_comparator(sanitized_query:, cursor:, order:, comparator:)
      Post.sanitize_sql_array([
                                <<~SQL,
                                  (SELECT * FROM posts WHERE content LIKE ? AND posts.id #{comparator} ?)
                                  UNION ALL
                                  (SELECT * FROM posts WHERE title LIKE ? AND posts.id #{comparator} ?)
                                  ORDER BY id #{order}
                                  LIMIT #{POSTS_PER_PAGE}
                                SQL
                                "#{sanitized_query}%", cursor, "#{sanitized_query}%", cursor
                              ])
    end
  end

  private

  def set_default_values
    self.title ||= '無題'
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    before_action :check_logged_in, only: %i[create]

    # POST /posts/:post_id/comments
    def create
      form = resolve_create_form
      if form.save
        flash[:success] = 'コメントが作成されました'
        redirect_to post_url(form.post)
      else
        flash[:alert] = "コメントの作成に失敗しました #{form.errors.full_messages.to_sentence}"
        render partial: 'posts/comments/form', locals: { post: form.post }, status: :unprocessable_entity
      end
    end

    private

    def create_params
      params.require(:comment).permit(:comment)
    end

    def resolve_create_form
      Comment::BuildForm.new(
        user_id: session[:user_id],
        post: Post.find(params[:post_id]),
        params: create_params
      )
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :check_logged_in, only: %i[index show new create]
  before_action :authorize_post_edit, only: %i[edit update destroy]

  # GET /posts
  def index
    resolve_pagination!
    @favorite_counts = resolve_favorite_counts(@posts)
    @favorites = resolve_favorites(@posts)
    @comment_counts = resolve_comment_counts(@posts)
    flash.now[:notice] = "#{@query}に該当する結果はありません" if @query.present? && @posts.empty?
  end

  # GET /posts/:id
  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @favorite_count = @post.favorites.count
    @favorite = current_user.favorites.find_by(post_id: @post.id)
    @comment = Comment.new
    @comments = @post.comments.preload(:user)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_url, notice: '投稿しました'
    else
      flash.now[:alert] = '投稿に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  # GET /posts/:id/edit
  def edit
    @post = current_user.posts.find_by(id: params[:id])
  end

  # PUT /posts/:id
  def update
    @post = current_user.posts.find_by(id: params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: '投稿内容を更新しました'
    else
      flash.now[:alert] = '投稿内容の更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/:id
  def destroy
    @post = current_user.posts.find_by(id: params[:id])

    if @post.destroy
      redirect_to posts_url, notice: '投稿を削除しました', status: :see_other
    else
      redirect_to @post, alert: '投稿の削除に失敗しました'
    end
  end

  private

  def authorize_post_edit
    post = Post.find_by(id: params[:id])
    check_edit_authority(user_id: post.user_id, redirect_url: post_url(post))
  end

  def post_params
    params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
  end

  def resolve_comment_counts(posts)
    Comment.where(post_id: posts.pluck(:id)).group(:post_id).count
  end

  def resolve_favorites(posts)
    current_user.favorites.where(post_id: posts.pluck(:id)).index_by(&:post_id)
  end

  def resolve_favorite_counts(posts)
    Favorite.where(post_id: posts.pluck(:id)).group(:post_id).count
  end

  def resolve_pagination!
    @query = params[:query]
    @last_post_id = params[:last_post_id]
    @first_post_id = params[:first_post_id]
    @posts, @next_cursor, @prev_cursor = Post.resolve_posts_with_pagination(
      query: @query,
      last_post_id: @last_post_id,
      first_post_id: @first_post_id
    )
  end
end

app/views/posts/_form.html.erb
<style>
  div.post-form-wrapper {
    width: 80%;
    margin: 0 auto;
  }

  form {
    width: 100%;
  }

  #post_title {
    min-height: 1rem;
  }

  .textarea {
    width: 100%;
    margin: 0;
    resize: none;
  }
</style>

<div class="post-form-wrapper">
  <div class="field is-grouped">
    <%= form_with(model: @post, local: true) do |form| %>
      <div>
        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>

      <div class="field">
        <label class="label"><%= form.label 'タイトル' %></label>
        <span class="title-box">
          <%= form.text_field :title, autofocus: true, class: 'textarea is-rounded', placeholder: 'タイトル', size: '30', maxlength: '30' %>
        </span>
      </div>

      <div class="field">
        <label class="label"><%= form.label '本文' %></label>
        <%= form.text_area :content, class: 'content-box textarea is-rounded', placeholder: '本文', size: '30x10', maxlength: '140' %>
      </div>

      <div class="field">
        <%= form.submit submit_word, class: 'button is-primary has-text-white is-rounded is-fullwidth' %>
      </div>

      <div class="field">
        <%= link_to 'キャンセル', back_path, class: 'button is-primary is-rounded is-outlined is-fullwidth' %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<article class="media">
  <div class="media-content">
    <div class="post-wrapper">
      <p><%= link_to post.user.email, user_path(post.user) %></p>
      <p><%= link_to post.title, post %></p>
      <p>
        <%= simple_format(post.content) %>
      </p>
      <p>
        <span>
          <%= link_to post_path(post) do %>
            <span class="material-icons", style="color: #4A9A98;">
              mode_comment
            </span>
          <% end %>
          <%= @comment_counts[post.id] || 0 %>
        </span>
        <span>
          <% if current_user.favorited?(post.id) %>
            <%= link_to post_favorite_path(post, @favorites[post.id]), data: { turbo_method: :delete } do %>
              <span class="material-icons has-text-danger">
                favorite
              </span>
            <% end %>
          <% else %>
            <%= link_to post_favorites_path(post), data: { turbo_method: :post } do %>
              <span class="material-icons has-text-grey">
                favorite_border
              </span>
            <% end %>
          <% end %>
          <span>
            <%= @favorite_counts[post.id] || 0 %>like
          </span>
        </span>
      </p>
    </div>
  </div>
</article>

app/views/posts/edit.html.erb
<% provide(:title, '投稿編集') %>

<div class="contents-wrapper">
  <h1>投稿編集</h1>

  <%= render 'layouts/flash' %>
  <%= render 'posts/form', { submit_word: '編集完了', back_path: post_path(@post) } %>
</div>

app/views/posts/index.html.erb
<% provide(:title, 'Home') %>
<style>
  div.search-box {
    display: flex;
  }
</style>

<div class="contents-wrapper">
  <h1>ポスト</h1>

  <%= render 'layouts/flash' %>

  <div class="field has-addons">
    <%= form_with url: posts_path, method: :get, local: true do |form| %>
      <div class="search-box">
        <span class="control">
          <%= form.text_field :query, class: 'input is-rounded', placeholder: 'キーワード', size: '140' %>
        </span>
        <span class="control">
          <%= form.submit '検索', class: 'button is-primary has-text-white is-rounded' %>
        </span>
      </div>
    <% end %>
  </div>

  <% if @posts.present? %>
    <% if @query.blank? %>
      <h2>すべてのポスト</h2>
    <% else %>
      <h2><%= @query %> の検索結果</h2>
    <% end %>
    <div class="posts">
      <%= render @posts %>
    </div>
  <% end %>

  <nav class="pagination" role="navigation" aria-label="pagination">
    <ul class="pagination-list">
      <li style="margin: 0;">
        <%= link_to '< prev', posts_path(first_post_id: @prev_cursor, query: params[:query]), class: 'pagination-previous' %>
      </li>

      <li style="margin: 0;">
        <%= link_to 'next >', posts_path(last_post_id: @next_cursor, query: params[:query]), class: 'pagination-next' %>
      </li>
    </ul>
  </nav>
</div>

app/views/posts/new.html.erb
<% provide(:title, '新規ポスト') %>

<div class="contents-wrapper">
  <h1>新規ポスト</h1>

  <%= render 'layouts/flash' %>
  <%= render 'posts/form', { submit_word: '投稿する', back_path: posts_path } %>
</div>

app/views/posts/show.html.erb
<% provide(:title, 'ポスト詳細' + @post.title) %>

<style>
  .field.has-addons {
    width: 100%;
  }

  div.control {
    width: 50%;
  }
</style>

<div class="contents-wrapper">
  <h1>ポスト詳細</h1>
  <%= render 'layouts/flash' %>

  <article class="media">
    <div class="media-content">
      <p>
        <strong><%= link_to @post.user.email, user_path(@post.user) %></strong>
      </p>
      <p><%= @post.title %></p>
      <p><%= simple_format(@post.content) %></p>
      <p>
        <small>投稿日時：<%= @post.created_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M:%S") %></small>
        <br>
        <small>更新日時：<%= @post.updated_at.in_time_zone('Tokyo').strftime("%Y-%m-%d %H:%M:%S") %></small>
      </p>
      <div>
        <%= render 'favorites/btn', { post: @post, favorite: @favorite, favorite_count: @favorite_count } %>
      </div>
    </div>
  </article>

  <div class="field has-addons">
    <% if session[:user_id] == @post.user_id %>
      <div class="control">
        <%= link_to 'ポスト編集', edit_post_path(@post.id), class: 'button is-primary has-text-white is-rounded is-fullwidth' %>
      </div>

      <div class="control">
        <%= link_to 'ポスト削除', post_path(@post.id), data: { turbo_method: :delete, turbo_confirm: '本当に削除しますか？' }, class: 'button is-danger has-text-white is-rounded is-fullwidth' %>
      </div>
    <% end %>
  </div>

  <div>
    <%= link_to 'ポスト一覧', posts_path, class: 'button is-primary is-outlined is-rounded is-fullwidth' %>
  </div>

  <%= render 'posts/comments/form', { post: @post } %>

  <h3>みんなのコメント</h3>
  <%= render 'posts/comments/comment', { comments: @comments } %>
</div>